# Generated by Django 2.1.4 on 2019-04-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myes', '0002_auto_20190405_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
